## host to bind, can also be passed via CLI args
# host = "127.0.0.1"

## port to bind, can also be passed via CLI args
# port = 8888

## whether to allow anyone to register an account
# open_registration = false

## Database Type, valid options are "postgres" and "sqlite"
# db_type = "sqlite"

## Database Connection string
# Sqlite Example
# db_uri="sqlite:///home/rigrassm/Development/atuin/config/data.db"
# Postgres Example
# db_uri="postgres://username:password@localhost/atuin"
